[package]
name = "hatim"
version = "0.1.0"
authors = ["assoft <macsonfor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.8.0"
chrono = "0.4.13"
rand = "0.7.3"
